use college_stagiaire;

SET GLOBAL FOREIGN_KEY_CHECKS=0;

INSERT INTO programme ( id, nom, dureeEnMois)
VALUES(1111111, 'INTELLIGENCE ARTIFICIELLE APPLIQUEE', 8);

INSERT INTO programme ( id, nom, dureeEnMois)
VALUES(2222222, 'PROGRAMMATION INFORMATIQUE', 24);

INSERT INTO programme ( id, nom, dureeEnMois)
VALUES(3333333, 'SOUTIEN TECHNIQUE EN INFORMATIQUE', 24);

INSERT INTO programme ( id, nom, dureeEnMois)
VALUES(4444444, 'TECHNIQUES DU GÉNIE ÉLECTRONIQUE', 24);

INSERT INTO programme ( id, nom, dureeEnMois)
VALUES(5555555, 'TECHNOLOGIE DU GÉNIE INFORMATIQUE', 24);

INSERT INTO programme ( id, nom, dureeEnMois)
VALUES(6666666, 'TECHNOLOGIE DU GÉNIE MÉCANIQUE', 24);

INSERT INTO programme ( id, nom, dureeEnMois)
VALUES(7777777, 'BACCALAURÉAT SPÉCIALISÉ EN BIOTECHNOLOGIE', 24);

INSERT INTO programme ( id, nom, dureeEnMois)
VALUES(8888888, 'BACCALAURÉAT EN SCIENCES INFIRMIÈRES', 24);

INSERT INTO programme ( id, nom, dureeEnMois)
VALUES(9999999, 'INITIATION AUX ARTS NUMÉRIQUES', 24);